version: '3'
services:
    api:
      build: backend
      ports:
        - "8000:8000"
    web-ui:
      build: ./frontend
      ports:
        - "3000:3000"
    auth:
      image: quay.io/pusher/oauth2_proxy:latest
      network_mode: "host"
      environment:
        - OAUTH2_PROXY_PROVIDER=oidc
        - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
        - OAUTH2_PROXY_CLIENT_ID=be3d8e5c-aaff-4cad-9a45-e0031058a478
        - OAUTH2_PROXY_CLIENT_SECRET=${CLIENT_SECRET}
        - OAUTH2_PROXY_COOKIE_SECRET=${COOKIE_SECRET}
        - OAUTH2_PROXY_SCOPE=openid User.Read https://graph.microsoft.com/User.Read email
        - OAUTH2_PROXY_REDIRECT_URL=http://localhost:7000/oauth2/callback
        - OAUTH2_PROXY_HTTP_ADDRESS=http://:7000
        - OAUTH2_PROXY_UPSTREAMS=http://:3000
        - OAUTH2_PROXY_COOKIE_REFRESH=60m
        - OAUTH2_PROXY_COOKIE_SECURE=false
        - OAUTH2_PROXY_EMAIL_DOMAINS=*
        - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
        - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=false
      ports:
        - "7000:7000"