apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: gathering-persephone
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: prod
  components:
    - name: backend
      src: backend
      ports:
       - name: http
         port: 8000
      publicPort: http
    - name: frontend
      src: frontend
      ports:
        - name: http
          port: 3000
      publicPort: http
      secrets: 
        - GOOGLE_API_KEY
  dnsAppAlias:
    environment: prod
    component: frontend
